### PR TITLE
Allow webconfig

### PR DESCRIPTION
**Pull request by negbie**

### CODE REVIEW

**Comment by games130** [comment]
Will you be providing some example or detail on this "Allow web config".
Sorry for asking because i don't understand how this works. try to look at the commit... still don't understand

**Comment by lmangani** [comment]
No worries @games130 features will be documented once they're complete and ready to use ;)

**Comment by games130** [comment]
ok! thank you

**Comment by negbie** [comment]
@games130 you can use the flag -confighttpaddr :2222. Browse to localhost:2222 in your web browser and you should see this:

Screenshot-2019-3-15 heplify-server web config

**Pull request merged**
