### PR TITLE
added support to parse custom headers

### PR DESCRIPTION
**Pull request by aqsyonas**
adding support to parse custom headers from the config file and save them into data_header table.

### CODE REVIEW

**Comment by negbie** [comment]
Just run following inside the sipparser folder

go test -bench=.

**Comment by negbie** [comment]
@aqsyounas thanks. Keep in mind that CustomHeaders will be renamed to CustomHeader.

**Comment by aqsyonas** [comment]
Thanks for merging the request and pointers above. I will surely keep in mind the change regarding CustomHeader.

**Comment by negbie** [comment]
Your welcome. I will soon push some changes where I will move the sipparser into this package. I will also allocate the map when len(s.CHeader) > 0 to improve performance a bit. Another point would be to think about moving the position of this block. This would allow the user to specify the headers he want in the SIP Data header. For example he could define record, via etc...

**Pull request merged**
