### PR TITLE
adjust ExecStart in service file to match package

### PR DESCRIPTION
**Pull request by kevin-olbrich**

### CODE REVIEW

**Comment by kevin-olbrich** [comment]
The pre-built packages use: /usr/local/bin/heplify-server
Also, the systemd files should be moved to /lib/systemd/system as /etc is for custom files only.

**Comment by negbie** [comment]
Hi @kevin-olbrich 
thank you! Could you please adjust the comment about /lib/systemd/system aswell?

**Comment by kevin-olbrich** [comment]
> Hi @kevin-olbrich
> thank you! Could you please adjust the comment about /lib/systemd/system aswell?

Do you mean, adding a commit that moves the service file to /lib/systemd/system aswell?

**Comment by negbie** [comment]
Yip ;)

**Comment by negbie** [comment]
Just this line # cp heplify-server.service /etc/systemd/system/

**Comment by kevin-olbrich** [comment]
> Just this line # cp heplify-server.service /etc/systemd/system/

Actually the file itself is correct. In case someone does a manual install, it's perfectly fine.
When distributed using packages, they belong to /lib.

I added a small comment in my last commit.

**Comment by negbie** [comment]
Thank you!

**Pull request merged**
