### PR TITLE
PgSQL dsn improvements

### PR DESCRIPTION
**Pull request by volga629-1**
Ticket reference: #437

### CODE REVIEW

**Comment by nathanleyton** [comment]
Hi I am happy to see find a PR for this as we really need it. Do we have a lead time on when this might be merged? Not having sslmode means we cannot use homer. Thanks

**Comment by negbie** [comment]
DBPort is a breaking change so can't merge.

**Comment by volga629-1** [comment]
> DBPort is a breaking change so can't merge.

Can you please point what exactly is not right ?

**Comment by negbie** [comment]
In the old config you use DBAddr as "localhost:1234" 
with your PR you use DBAddr as "localhost" and DBPort "1234"

**Comment by volga629-1** [comment]
Yes, DBPort is part of pull request, I added corresponding options to config.go.
My pull request I added to spec file and everything works as expected. I am not sure what actually is breaks.
It just separate option for host and port  to make dsn more flexible.

**Comment by negbie** [comment]
There are alot of users who have config files with DBAddr set to for example "localhost:1234".

**Comment by lmangani** [comment]
Fully agree with @negbie there's no reason to break backwards compatibility for such a minimal change with no particular advantage. @volga629-1 could you merge those back or make the second an optional parameter to retain compatibility?

**Comment by ZionDials** [comment]
Hello, I created a pull request that allows SSL Mode for the DB Connection without breaking backward compatibility. #449

**Review by lmangani — APPROVED** [review]

**Comment by negbie** [comment]
Guys, you should read more carefully, this PR should be approved but ZionDials PR https://github.com/sipcapture/heplify-server/pull/449

**Comment by adubovikov** [comment]
@negbie oki! thanks for pointing :)

**Comment by negbie** [comment]
https://github.com/sipcapture/heplify-server/pull/449 was merged so closing this. Thanks @volga629-1 for bringing this up.

**Pull request closed without merging**
