### PR TITLE
add Expires header + modify XCallID

### PR DESCRIPTION
**Pull request by games130**
Added to extract Expires header from SIP message

XCallID to be able to use regex to further extract correct valid. Example for P-Charging-Vector

P-Charging-Vector: icid-value=\"somevalue\";orig-ioi=host.domain.com

will want to extract "somevalue" instead of the whole string.
Suggested format to add the regex. Regex need to have group construct (   ):
current toml:        AlegIDs    = ["X-CID","P-Charging-Vector"]
suggested toml:  AlegIDs     = ["X-CID","P-Charging-Vector,icid-value=\"(.*)\""]

note: please ignore the 13 commits, there are changes i did and i reverted it all back to match the current master. Do not know how to create a PR without all the 13 commit previously done.
The only changes are to 
sipparser/parser.go
sipparser/parser_test.go

### CODE REVIEW

**Comment by negbie** [comment]
@games130 thanks. Could you please revisit your pr because there is code which does more than you describe.

**Comment by games130** [comment]
@negbie could you help point out which part?

**Comment by negbie** [comment]
Just saw the commit list

@games130
self performance calculation …
8e14f7c
@games130
sipparser support Expires header …
63f347f
@games130
pkt.SIP.StartLine.Method not in used anymore …
61c409f
@games130
fix import for prometheus.go
54633f7
@games130
fix import for prometheus.go
131d7ee
@games130
Update README.md
59a9399
@games130
Update README.md
e9194d0
@games130
Add files via upload
e359c9e
@games130
Add files via upload
68a905f
@games130
Add files via upload
2bb6431
@games130
Add files via upload
dd6154d
@games130
Merge pull request #2 from sipcapture/master …
69ff42a
@games130
add Expires header + modify XCallID

**Comment by negbie** [comment]
Did not looked in detail into it.

**Comment by games130** [comment]
owww please do ignore the commit list... what happen was.. i fork the project and play around with some changes.. then i wanted to submit this PR so i commit everything from the master branch before making the new changes.. So if u look at the file changes, it is only those two file.

I do not know how to get a fresh new copy from sipcapture/heplify-server:master thats what lead to you seeing so many commits.

**Comment by negbie** [comment]
@games130 no problem. Could you please rebase it so I can evaluate only the change you need. Currently I don't have that much time to assist here. Another thing that I noticed is that you spilt the Header and compile the regex everytime. Doing it this way is quite slow and slould be improved.

**Comment by games130** [comment]
New pull request with changes as discuss #301.
Will close this one due to messy PR.

**Pull request closed without merging**
