### PR TITLE
rotation done by heplify-server

### PR DESCRIPTION
**Pull request by games130**
Trying to contribute for the first time, please do let me know if i done it the wrong way.
I am trying to improve on the rotation done by heplify-server. (i am testing on mysql only, have try to minimise any effect on pgsql)

mysql partition need at least 1 partition created, therefore need additional input so that the right partition can be created (duration and step)
- this means different table creation need to be split up from tbldata.sql into tbldatalog.sql, tbldatasip.sql and tbldataqos.sql

Change starttime to endtime. Assume step is 1hour for the partition because
- pnr0 should be 0000h - 0100h
- pnr1 should be 0100h - 0200h

Therefore need to use endtime not starttime (for parsip.sql, parlog.sql and parqos.sql)

### CODE REVIEW

**Comment by negbie** [comment]
@games130 Did you signed the CLA with your Github email address?

**Comment by games130** [comment]
i did sign it but it does not seem to taken effect. I am not sure why

**Comment by games130** [comment]
let me try to create a new pull request again.. mabye i did something wrong for the email because i cannot find what email it was.

**Comment by negbie** [comment]
@games did you test my latest changes?

**Comment by games130** [comment]
not yet, my database got corrupted today due to full disk usage over the weekend. was trying to figure out how to save it. I will have a test for the new changes 😀

**Comment by negbie** [comment]
Uh shit ;) Did you forget to set DBDropDays > 0? About my changes. I reverted the UTC stuff and use localtime now. That was not working before because I've used the wrong time format. Now I use

Format("2006-01-02 15:04:05-07:00")

Which sends the timezone too.
pnr0 should be 0000h should be fine too because its less 0000h. Since we use for mysql tables on daily basis this partition should be ignored.

**Pull request closed without merging**
